spring:
  datasource:
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_room?serverTimezone=UTC&characterEncoding=utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.thechatroom.mapper: debug
